import type { ChordPitch, EtudeBar, EtudeNote, StringId } from './models';
import type { SorEtude } from './models';
import { getFretMidi } from '../theory/note';

// Helpers — keep the catalog readable.
// `s` = string number (1=high E .. 6=low E), matches the rest of the codebase.

type CatalogString = 1 | 2 | 3 | 4 | 5 | 6;

function n(opts: {
  s: CatalogString;
  f: number;
  d: EtudeNote['duration'];
  lh?: EtudeNote['lhFinger'];
  rh?: EtudeNote['rhFinger'];
  dot?: boolean;
  tie?: boolean;
}): EtudeNote {
  // getFretMidi numbers strings 1=low E .. 6=high E internally; the catalog
  // uses 1=high E (consistent with Scales). Flip at the boundary.
  return {
    kind: 'note',
    duration: opts.d,
    dotted: opts.dot,
    tieToNext: opts.tie,
    stringId: opts.s,
    fret: opts.f,
    midi: getFretMidi(7 - opts.s, opts.f),
    lhFinger: opts.lh ?? null,
    rhFinger: opts.rh ?? null,
  };
}

// Build a chord tickable. `top` is the primary (typically the melody / top
// pitch); `others` are stacked simultaneously on the same beat. Renderer
// passes the merged set to VexFlow as `StaveNote.keys[]` / `TabNote.positions[]`.
function chord(opts: {
  top: { s: CatalogString; f: number; lh?: EtudeNote['lhFinger']; rh?: EtudeNote['rhFinger'] };
  others: { s: CatalogString; f: number; lh?: EtudeNote['lhFinger'] }[];
  d: EtudeNote['duration'];
  dot?: boolean;
  tie?: boolean;
}): EtudeNote {
  const extras: ChordPitch[] = opts.others.map(o => ({
    stringId: o.s as StringId,
    fret: o.f,
    midi: getFretMidi(7 - o.s, o.f),
    lhFinger: o.lh ?? null,
  }));
  return {
    ...n({
      s: opts.top.s,
      f: opts.top.f,
      d: opts.d,
      lh: opts.top.lh,
      rh: opts.top.rh,
      dot: opts.dot,
      tie: opts.tie,
    }),
    chord: extras,
  };
}

function rest(d: EtudeNote['duration'], dot = false): EtudeNote {
  return { kind: 'rest', duration: d, dotted: dot };
}

// ── Op. 60 No. 1 ─────────────────────────────────────────────────────────────
// Generated by `npm run import-etude -- --xml zmelodyhelper/sor/Op60_1.musicxml`
// from a MuseScore Studio 4.6.5 export. Andante, C major, 4/4, 16 bars.
// Phrase 1 (m1–m8) alternates a `h + q + q` triadic figure with stepwise
// quarter motion, peaking on F♯ in m7 and half-cadencing on V in m8.
// Phrase 2 (m9–m16) develops the same material in steady quarters and
// resolves on a tonic chord in m16. m8 and m16 use the new `chord()` helper
// to stack three pitches on a single beat.

const OP60_NO1_BARS: EtudeBar[] = [
  // m1
  {
    upper: [
      n({ s: 2, f: 1, d: 'h', lh: 1 }),   // C4
      n({ s: 2, f: 0, d: 'q' }),          // B3
      n({ s: 3, f: 0, d: 'q' }),          // G3
    ],
    lower: [],
  },
  // m2
  {
    upper: [
      n({ s: 2, f: 1, d: 'h', lh: 1 }),   // C4
      n({ s: 2, f: 0, d: 'q' }),          // B3
      n({ s: 3, f: 0, d: 'q' }),          // G3
    ],
    lower: [],
  },
  // m3
  {
    upper: [
      n({ s: 2, f: 1, d: 'q', lh: 1 }),   // C4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),   // D4
      n({ s: 1, f: 0, d: 'q' }),          // E4
      n({ s: 1, f: 3, d: 'q', lh: 3 }),   // G4
    ],
    lower: [],
  },
  // m4
  {
    upper: [
      n({ s: 1, f: 1, d: 'q', lh: 1 }),   // F4
      n({ s: 1, f: 0, d: 'q' }),          // E4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),   // D4
      n({ s: 3, f: 0, d: 'q' }),          // G3
    ],
    lower: [],
  },
  // m5
  {
    upper: [
      n({ s: 2, f: 1, d: 'h', lh: 1 }),   // C4
      n({ s: 2, f: 0, d: 'q' }),          // B3
      n({ s: 3, f: 0, d: 'q' }),          // G3
    ],
    lower: [],
  },
  // m6
  {
    upper: [
      n({ s: 2, f: 1, d: 'q', lh: 1 }),   // C4
      n({ s: 1, f: 0, d: 'q' }),          // E4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),   // D4
      n({ s: 2, f: 0, d: 'q' }),          // B3
    ],
    lower: [],
  },
  // m7 — peak with the printed F♯ + #3 fingering
  {
    upper: [
      n({ s: 3, f: 2, d: 'q', lh: 2 }),   // A3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),   // C4
      n({ s: 4, f: 0, d: 'q' }),          // D3
      n({ s: 1, f: 2, d: 'q', lh: 3 }),   // F#4
    ],
    lower: [],
  },
  // m8 — half cadence on V: G4 quarter, G-major chord, low G2, quarter rest.
  // Closes the first section with a backward repeat (||:..:||).
  {
    upper: [
      n({ s: 1, f: 3, d: 'q', lh: 4 }),   // G4
      chord({ top: { s: 2, f: 0 }, others: [{ s: 4, f: 0 }, { s: 3, f: 0 }], d: 'q' }),   // B3 + D3 + G3
      n({ s: 6, f: 3, d: 'q', lh: 3 }),   // G2
      rest('q'),
    ],
    lower: [],
    endRepeat: true,
  },
  // m9 — opens the second section with a forward repeat.
  {
    upper: [
      n({ s: 1, f: 3, d: 'q', lh: 4 }),   // G4
      n({ s: 3, f: 0, d: 'q' }),          // G3
      n({ s: 1, f: 0, d: 'q' }),          // E4
      n({ s: 1, f: 3, d: 'q', lh: 4 }),   // G4
    ],
    lower: [],
    startRepeat: true,
  },
  // m10
  {
    upper: [
      n({ s: 1, f: 1, d: 'q', lh: 1 }),   // F4
      n({ s: 3, f: 0, d: 'q' }),          // G3
      n({ s: 2, f: 3, d: 'q', lh: 4 }),   // D4
      n({ s: 1, f: 1, d: 'q', lh: 1 }),   // F4
    ],
    lower: [],
  },
  // m11
  {
    upper: [
      n({ s: 1, f: 0, d: 'q' }),          // E4
      n({ s: 3, f: 0, d: 'q' }),          // G3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),   // C4
      n({ s: 1, f: 0, d: 'q' }),          // E4
    ],
    lower: [],
  },
  // m12
  {
    upper: [
      n({ s: 2, f: 3, d: 'q', lh: 4 }),   // D4
      n({ s: 2, f: 0, d: 'q' }),          // B3
      n({ s: 3, f: 0, d: 'q' }),          // G3
      n({ s: 4, f: 3, d: 'q', lh: 3 }),   // F3
    ],
    lower: [],
  },
  // m13
  {
    upper: [
      n({ s: 4, f: 2, d: 'q', lh: 2 }),   // E3
      n({ s: 3, f: 0, d: 'q' }),          // G3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),   // C4
      n({ s: 4, f: 2, d: 'q', lh: 2 }),   // E3
    ],
    lower: [],
  },
  // m14
  {
    upper: [
      n({ s: 4, f: 3, d: 'q', lh: 3 }),   // F3
      n({ s: 3, f: 2, d: 'q', lh: 2 }),   // A3
      n({ s: 4, f: 0, d: 'q' }),          // D3
      n({ s: 4, f: 3, d: 'q', lh: 3 }),   // F3
    ],
    lower: [],
  },
  // m15
  {
    upper: [
      n({ s: 4, f: 2, d: 'q', lh: 2 }),   // E3
      n({ s: 3, f: 0, d: 'q' }),          // G3
      n({ s: 6, f: 3, d: 'q', lh: 3 }),   // G2
      n({ s: 5, f: 2, d: 'q', lh: 2 }),   // B2
    ],
    lower: [],
  },
  // m16 — final tonic cadence: low C3, C-major chord, low C3, quarter rest.
  // Closes the second section with a backward repeat.
  {
    upper: [
      n({ s: 5, f: 3, d: 'q', lh: 3 }),   // C3
      chord({ top: { s: 1, f: 0 }, others: [{ s: 3, f: 0 }, { s: 2, f: 1, lh: 1 }], d: 'q' }),   // E4 + G3 + C4
      n({ s: 5, f: 3, d: 'q', lh: 3 }),   // C3
      rest('q'),
    ],
    lower: [],
    endRepeat: true,
  },
];

export const SOR_OP60_NO1: SorEtude = {
  id: 'sor-op60-no1',
  opus: 60,
  number: 1,
  title: 'Op. 60 No. 1',
  key: 'C',
  keyMode: 'Ionian',
  timeSignature: '4/4',
  defaultBpm: 72,
  bars: OP60_NO1_BARS,
  enabled: true,
  attribution:
    'Sor — 25 Progressive Studies, Op. 60, No. 1. Imported from MuseScore Studio export of the bundled beginner PDF (page 12). Public domain.',
};

// ── Op. 60 No. 2 ─────────────────────────────────────────────────────────────
// Transcribed from `zMelodyHelper/sor/Op60_2.musicxml` (MuseScore Studio 4.6.5
// export). C major, 3/4, 40 bars. Single-voice throughout except the closing
// cadence (m38–m40) which adds an independent bass line in `lower`.
// Chromatic colour: C# (m8, m28), F# (m21), G# (m34).

const OP60_NO2_BARS: EtudeBar[] = [
  // m1
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 1, f: 0, d: 'q' }),         // E4
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
    ],
    lower: [],
  },
  // m2
  {
    upper: [
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 2, f: 0, d: '8' }),         // B3
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m3
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m4
  {
    upper: [
      n({ s: 2, f: 3, d: 'q', lh: 3 }),  // D4
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 2, f: 3, d: '8', lh: 4 }),  // D4
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m5
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m6
  {
    upper: [
      n({ s: 1, f: 3, d: 'q', lh: 4 }),  // G4
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
      n({ s: 2, f: 3, d: '8', lh: 4 }),  // D4
      n({ s: 2, f: 0, d: '8' }),         // B3
    ],
    lower: [],
  },
  // m7
  {
    upper: [
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m8 — chromatic C# resolves down to natural C
  {
    upper: [
      n({ s: 2, f: 2, d: 'q', lh: 2 }),  // C#4
      n({ s: 2, f: 3, d: '8', lh: 4 }),  // D4
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 2, f: 0, d: '8' }),         // B3
      n({ s: 3, f: 2, d: '8', lh: 2 }),  // A3
    ],
    lower: [],
  },
  // m9
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 1, f: 0, d: 'q' }),         // E4
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
    ],
    lower: [],
  },
  // m10
  {
    upper: [
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 2, f: 0, d: '8' }),         // B3
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m11
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m12
  {
    upper: [
      n({ s: 2, f: 3, d: 'q', lh: 3 }),  // D4
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 2, f: 3, d: '8', lh: 4 }),  // D4
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m13
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m14
  {
    upper: [
      n({ s: 1, f: 3, d: 'q', lh: 4 }),  // G4
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m15
  {
    upper: [
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 3, f: 0, d: '8' }),         // G3
      n({ s: 1, f: 0, d: 'q' }),         // E4
      n({ s: 2, f: 3, d: '8', lh: 4 }),  // D4
      n({ s: 2, f: 0, d: '8' }),         // B3
    ],
    lower: [],
  },
  // m16 — low C3 punctuates the cadence
  {
    upper: [
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 5, f: 3, d: 'q', lh: 3 }),  // C3
      rest('q'),
    ],
    lower: [],
  },
  // m17
  {
    upper: [
      n({ s: 2, f: 0, d: 'q' }),         // B3
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m18
  {
    upper: [
      n({ s: 2, f: 1, d: 'h', lh: 1 }),  // C4
      n({ s: 3, f: 2, d: 'q', lh: 2 }),  // A3
    ],
    lower: [],
  },
  // m19
  {
    upper: [
      n({ s: 4, f: 0, d: 'q' }),         // D3
      n({ s: 3, f: 2, d: 'q', lh: 2 }),  // A3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
    ],
    lower: [],
  },
  // m20
  {
    upper: [
      n({ s: 2, f: 0, d: 'h' }),         // B3
      n({ s: 3, f: 0, d: 'q' }),         // G3
    ],
    lower: [],
  },
  // m21 — chromatic F# then natural F
  {
    upper: [
      n({ s: 1, f: 3, d: 'q', lh: 4 }),  // G4
      n({ s: 1, f: 2, d: 'q', lh: 2 }),  // F#4
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
    ],
    lower: [],
  },
  // m22
  {
    upper: [
      n({ s: 1, f: 0, d: 'q' }),         // E4
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 3, f: 2, d: 'q', lh: 2 }),  // A3
    ],
    lower: [],
  },
  // m23
  {
    upper: [
      n({ s: 2, f: 0, d: '8' }),         // B3
      n({ s: 4, f: 0, d: '8' }),         // D3
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 3, f: 2, d: '8', lh: 2 }),  // A3
    ],
    lower: [],
  },
  // m24 — low G2 punctuation, mirrors m16
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 6, f: 3, d: 'q', lh: 3 }),  // G2
      rest('q'),
    ],
    lower: [],
  },
  // m25
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 0, d: 'q' }),         // B3
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m26
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m27
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m28
  {
    upper: [
      n({ s: 2, f: 3, d: '8', lh: 4 }),  // D4
      n({ s: 2, f: 2, d: '8', lh: 2 }),  // C#4
      n({ s: 2, f: 3, d: '8', lh: 4 }),  // D4
      n({ s: 2, f: 0, d: '8' }),         // B3
      n({ s: 3, f: 0, d: 'q' }),         // G3
    ],
    lower: [],
  },
  // m29
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 0, d: '8' }),         // B3
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 2, f: 3, d: 'q', lh: 4 }),  // D4
    ],
    lower: [],
  },
  // m30
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
      n({ s: 2, f: 3, d: '8', lh: 3 }),  // D4
      n({ s: 1, f: 0, d: 'q' }),         // E4
    ],
    lower: [],
  },
  // m31
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 2, f: 3, d: '8', lh: 3 }),  // D4
      n({ s: 1, f: 1, d: '8', lh: 1 }),  // F4
      n({ s: 1, f: 0, d: '8' }),         // E4
      n({ s: 2, f: 1, d: '8', lh: 1 }),  // C4
    ],
    lower: [],
  },
  // m32
  {
    upper: [
      n({ s: 2, f: 3, d: 'h', lh: 3 }),  // D4
      n({ s: 3, f: 0, d: 'q' }),         // G3
    ],
    lower: [],
  },
  // m33
  {
    upper: [
      n({ s: 1, f: 0, d: 'q' }),         // E4
      n({ s: 2, f: 3, d: 'q', lh: 3 }),  // D4
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
    ],
    lower: [],
  },
  // m34 — chromatic G# leading tone into A
  {
    upper: [
      n({ s: 2, f: 0, d: 'q' }),         // B3
      n({ s: 3, f: 1, d: 'q', lh: 1 }),  // G#3
      n({ s: 3, f: 2, d: 'q', lh: 2 }),  // A3
    ],
    lower: [],
  },
  // m35
  {
    upper: [
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
      n({ s: 1, f: 0, d: 'q' }),         // E4
      n({ s: 2, f: 3, d: 'q', lh: 3 }),  // D4
    ],
    lower: [],
  },
  // m36
  {
    upper: [
      n({ s: 2, f: 1, d: 'h', lh: 1 }),  // C4
      n({ s: 2, f: 0, d: 'q' }),         // B3
    ],
    lower: [],
  },
  // m37
  {
    upper: [
      n({ s: 3, f: 0, d: 'q' }),         // G3
      n({ s: 1, f: 3, d: 'q', lh: 3 }),  // G4
      n({ s: 1, f: 1, d: 'q', lh: 1 }),  // F4
    ],
    lower: [],
  },
  // m38 — final cadence opens; melody on top, ascending bass line C–D–E below
  {
    upper: [
      n({ s: 1, f: 0, d: 'q' }),         // E4
      n({ s: 2, f: 0, d: 'q' }),         // B3
      n({ s: 2, f: 1, d: 'q', lh: 1 }),  // C4
    ],
    lower: [
      n({ s: 5, f: 3, d: 'q', lh: 3 }),  // C3
      n({ s: 4, f: 0, d: 'q' }),         // D3
      n({ s: 4, f: 2, d: 'q', lh: 2 }),  // E3
    ],
  },
  // m39 — bass holds F3 across the bar
  {
    upper: [
      n({ s: 2, f: 3, d: 'q', lh: 3 }),  // D4
      n({ s: 3, f: 2, d: 'q', lh: 2 }),  // A3
      n({ s: 2, f: 0, d: 'q' }),         // B3
    ],
    lower: [
      n({ s: 4, f: 3, d: 'h', lh: 3 }),  // F3
      n({ s: 3, f: 0, d: 'q' }),         // G3
    ],
  },
  // m40 — final tonic resolution (source closes with a light-heavy barline)
  {
    upper: [
      n({ s: 2, f: 1, d: 'h', lh: 1 }),  // C4
      rest('q'),
    ],
    lower: [
      n({ s: 5, f: 3, d: 'h', lh: 3 }),  // C3
      rest('q'),
    ],
  },
];

export const SOR_OP60_NO2: SorEtude = {
  id: 'sor-op60-no2',
  opus: 60,
  number: 2,
  title: 'Op. 60 No. 2',
  key: 'C',
  keyMode: 'Ionian',
  timeSignature: '3/4',
  defaultBpm: 72,
  bars: OP60_NO2_BARS,
  enabled: true,
  attribution:
    'Sor — 25 Progressive Studies, Op. 60, No. 2. Transcribed from MuseScore Studio export. Public domain.',
};

// Future etudes — registered but disabled so the UI can show the full Op. 60
// roster as a roadmap. Add bars + flip `enabled` to publish one.
function stub(num: number): SorEtude {
  return {
    id: `sor-op60-no${num}`,
    opus: 60,
    number: num,
    title: `Op. 60 No. ${num}`,
    key: 'C',
    keyMode: 'Ionian',
    timeSignature: '2/4',
    defaultBpm: 72,
    bars: [],
    enabled: false,
  };
}

export const SOR_ETUDES: SorEtude[] = [
  SOR_OP60_NO1,
  SOR_OP60_NO2,
  ...Array.from({ length: 23 }, (_, i) => stub(i + 3)),
];

export function getEtudeById(id: string): SorEtude | undefined {
  return SOR_ETUDES.find(e => e.id === id);
}

export function etudeLabel(e: SorEtude): string {
  return e.title;
}
